/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panelPrincipal;

import subPanel.pnlConfiguracion2;
import subPanel.pnlConfiguracion1;
import subPanel.pnlConfiguracion4;
import subPanel.pnlConfiguracion3;
import clase.CambiaPanel;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Rodri
 */
public class pnlConfiguracion extends javax.swing.JPanel {

    /**
     * Creates new form pnlConfiguracion
     */
    public pnlConfiguracion() {
        initComponents();
        
        new CambiaPanel(pnlContainer, new pnlConfiguracion1());
    }

    
    //Funcion Para el cambio de color al mantener y soltar un elemento
    public void cambioColor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMaquinaria = new javax.swing.JPanel();
        lblMaquinaria = new javax.swing.JLabel();
        btnEspecies = new javax.swing.JPanel();
        lblEspecies = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        btnRol = new javax.swing.JPanel();
        lblRol = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(242, 242, 242));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(225, 232, 193));
        jPanel1.setPreferredSize(new java.awt.Dimension(725, 50));

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMaquinaria.setBackground(new java.awt.Color(242, 242, 242));

        lblMaquinaria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaquinaria.setForeground(new java.awt.Color(51, 51, 55));
        lblMaquinaria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaquinaria.setText("Maquinaria");
        lblMaquinaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMaquinariaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMaquinariaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMaquinariaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMaquinariaLayout = new javax.swing.GroupLayout(btnMaquinaria);
        btnMaquinaria.setLayout(btnMaquinariaLayout);
        btnMaquinariaLayout.setHorizontalGroup(
            btnMaquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMaquinaria, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );
        btnMaquinariaLayout.setVerticalGroup(
            btnMaquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMaquinaria, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnMaquinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        btnEspecies.setBackground(new java.awt.Color(242, 242, 242));

        lblEspecies.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEspecies.setForeground(new java.awt.Color(51, 51, 55));
        lblEspecies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEspecies.setText("Especies");
        lblEspecies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEspeciesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEspeciesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEspeciesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEspeciesLayout = new javax.swing.GroupLayout(btnEspecies);
        btnEspecies.setLayout(btnEspeciesLayout);
        btnEspeciesLayout.setHorizontalGroup(
            btnEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEspecies, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        btnEspeciesLayout.setVerticalGroup(
            btnEspeciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEspecies, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnEspecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 125, -1));

        btnUsuario.setBackground(new java.awt.Color(242, 242, 242));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(51, 51, 55));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Usuarios");
        lblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnUsuarioLayout = new javax.swing.GroupLayout(btnUsuario);
        btnUsuario.setLayout(btnUsuarioLayout);
        btnUsuarioLayout.setHorizontalGroup(
            btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );
        btnUsuarioLayout.setVerticalGroup(
            btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 0, -1, -1));

        btnRol.setBackground(new java.awt.Color(242, 242, 242));
        btnRol.setForeground(new java.awt.Color(51, 51, 55));

        lblRol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRol.setForeground(new java.awt.Color(51, 51, 55));
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRol.setText("Rol de usuarios");
        lblRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRolMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRolLayout = new javax.swing.GroupLayout(btnRol);
        btnRol.setLayout(btnRolLayout);
        btnRolLayout.setHorizontalGroup(
            btnRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnRolLayout.setVerticalGroup(
            btnRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRol, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 0, 130, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlContainer.setBackground(new java.awt.Color(225, 232, 193));
        pnlContainer.setLayout(new javax.swing.BoxLayout(pnlContainer, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane2.setViewportView(pnlContainer);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void lblEspeciesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEspeciesMouseClicked
        new CambiaPanel(pnlContainer, new pnlConfiguracion1());
    }//GEN-LAST:event_lblEspeciesMouseClicked

    private void lblMaquinariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaquinariaMouseClicked
        CambiaPanel cambiaPanel = new CambiaPanel(pnlContainer, new pnlConfiguracion2());
    }//GEN-LAST:event_lblMaquinariaMouseClicked

    private void lblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseClicked
        new CambiaPanel(pnlContainer, new pnlConfiguracion3());
    }//GEN-LAST:event_lblUsuarioMouseClicked

    private void lblRolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRolMouseClicked
        new CambiaPanel(pnlContainer, new pnlConfiguracion4());
    }//GEN-LAST:event_lblRolMouseClicked

    /* Btn Especies */
    private void lblEspeciesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEspeciesMouseExited
        cambioColor(btnEspecies, new Color(242,242,242));
    }//GEN-LAST:event_lblEspeciesMouseExited

    private void lblEspeciesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEspeciesMouseEntered
        cambioColor(btnEspecies, new Color(204,204,204));
    }//GEN-LAST:event_lblEspeciesMouseEntered

    /* Btn Maquinaria */
    private void lblMaquinariaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaquinariaMouseExited
        cambioColor(btnMaquinaria, new Color(242,242,242));
    }//GEN-LAST:event_lblMaquinariaMouseExited

    private void lblMaquinariaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaquinariaMouseEntered
        cambioColor(btnMaquinaria, new Color(204,204,204));
    }//GEN-LAST:event_lblMaquinariaMouseEntered

    /* Btn Usuario */
    private void lblUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseExited
        cambioColor(btnUsuario, new Color(242,242,242));
    }//GEN-LAST:event_lblUsuarioMouseExited

    private void lblUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseEntered
        cambioColor(btnUsuario, new Color(204,204,204));
    }//GEN-LAST:event_lblUsuarioMouseEntered

    /* Btn Rol */
    private void lblRolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRolMouseExited
        cambioColor(btnRol, new Color(242,242,242));
    }//GEN-LAST:event_lblRolMouseExited

    private void lblRolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRolMouseEntered
        cambioColor(btnRol, new Color(204,204,204));
    }//GEN-LAST:event_lblRolMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnEspecies;
    private javax.swing.JPanel btnMaquinaria;
    private javax.swing.JPanel btnRol;
    private javax.swing.JPanel btnUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEspecies;
    private javax.swing.JLabel lblMaquinaria;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlContainer;
    // End of variables declaration//GEN-END:variables
}
