package yumsystem;

import javax.swing.JOptionPane;
import modelo.B_FAQ;
import controlador.B_FAQC;

public class frmBodega3 extends javax.swing.JFrame {

    /**
     * Creates new form frmBodega3
     */
    public frmBodega3() {
        initComponents();
          setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFechaRiego = new javax.swing.JLabel();
        txtNombre = new RSMaterialComponent.RSTextFieldMaterial();
        lblHoraRiego = new javax.swing.JLabel();
        lblPersonalRiego = new javax.swing.JLabel();
        txtMax = new RSMaterialComponent.RSTextFieldMaterial();
        guardar = new newscomponents.RSButtonFlat_new();
        btnCancelarRiego1 = new newscomponents.RSButtonFlat_new();
        txtAct = new RSMaterialComponent.RSTextFieldMaterial();
        lblHoraRiego1 = new javax.swing.JLabel();
        btnAGRO = new RSMaterialComponent.RSRadioButtonMaterial();
        btnFER = new RSMaterialComponent.RSRadioButtonMaterial();
        lblPersonalRiego1 = new javax.swing.JLabel();
        btnActivo = new RSMaterialComponent.RSRadioButtonMaterial();
        btnInactivo = new RSMaterialComponent.RSRadioButtonMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(149, 160, 95));

        lblFechaRiego.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaRiego.setText("Nombre:");

        txtNombre.setBackground(new java.awt.Color(242, 242, 242));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setColorMaterial(new java.awt.Color(0, 114, 81));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNombre.setPhColor(new java.awt.Color(102, 102, 102));
        txtNombre.setPlaceholder("Fertilizante y agroquimico");
        txtNombre.setSelectionColor(new java.awt.Color(0, 114, 81));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        lblHoraRiego.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHoraRiego.setText("Cantidad maxima:");

        lblPersonalRiego.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPersonalRiego.setText("Tipo:");

        txtMax.setBackground(new java.awt.Color(242, 242, 242));
        txtMax.setForeground(new java.awt.Color(0, 0, 0));
        txtMax.setColorMaterial(new java.awt.Color(0, 114, 81));
        txtMax.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMax.setPhColor(new java.awt.Color(102, 102, 102));
        txtMax.setPlaceholder("Maximo");
        txtMax.setSelectionColor(new java.awt.Color(0, 114, 81));
        txtMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaxKeyTyped(evt);
            }
        });

        guardar.setBackground(new java.awt.Color(0, 114, 81));
        guardar.setText("Guardar");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });

        btnCancelarRiego1.setBackground(new java.awt.Color(0, 114, 81));
        btnCancelarRiego1.setText("Cancelar");
        btnCancelarRiego1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarRiego1MouseClicked(evt);
            }
        });

        txtAct.setBackground(new java.awt.Color(242, 242, 242));
        txtAct.setForeground(new java.awt.Color(0, 0, 0));
        txtAct.setColorMaterial(new java.awt.Color(0, 114, 81));
        txtAct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAct.setPhColor(new java.awt.Color(102, 102, 102));
        txtAct.setPlaceholder("Actual");
        txtAct.setSelectionColor(new java.awt.Color(0, 114, 81));
        txtAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtActKeyTyped(evt);
            }
        });

        lblHoraRiego1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHoraRiego1.setText("Cantidad Actual:");

        buttonGroup1.add(btnAGRO);
        btnAGRO.setForeground(new java.awt.Color(0, 114, 81));
        btnAGRO.setText("Agroquimico");
        btnAGRO.setColorCheck(new java.awt.Color(122, 201, 104));
        btnAGRO.setColorUnCheck(new java.awt.Color(0, 114, 81));
        btnAGRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAGROActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnFER);
        btnFER.setForeground(new java.awt.Color(0, 114, 81));
        btnFER.setText("Fertilizante");
        btnFER.setColorCheck(new java.awt.Color(122, 201, 104));
        btnFER.setColorUnCheck(new java.awt.Color(0, 114, 81));

        lblPersonalRiego1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPersonalRiego1.setText("Estado");

        buttonGroup2.add(btnActivo);
        btnActivo.setForeground(new java.awt.Color(0, 114, 81));
        btnActivo.setText("Activo");
        btnActivo.setColorCheck(new java.awt.Color(122, 201, 104));
        btnActivo.setColorUnCheck(new java.awt.Color(0, 114, 81));

        buttonGroup2.add(btnInactivo);
        btnInactivo.setForeground(new java.awt.Color(0, 114, 81));
        btnInactivo.setText("Inactivo");
        btnInactivo.setColorCheck(new java.awt.Color(122, 201, 104));
        btnInactivo.setColorUnCheck(new java.awt.Color(0, 114, 81));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPersonalRiego)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaRiego)
                                    .addComponent(lblHoraRiego))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHoraRiego1)
                                    .addComponent(txtAct, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFER, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAGRO, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarRiego1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPersonalRiego1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnInactivo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFechaRiego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraRiego)
                    .addComponent(lblHoraRiego1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPersonalRiego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFER, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAGRO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPersonalRiego1)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInactivo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarRiego1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCancelarRiego1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarRiego1MouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarRiego1MouseClicked

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
 /*Cambiar el modelo*/
        modelo.B_FAQ BF = new modelo.B_FAQ();
        /*Aplicar los set correspondientes al modelo*/
        BF.setNombre(this.txtNombre.getText());
      BF.setCantidad_Actual(Double.parseDouble(this.txtAct.getText()));
      BF.setCantidad_Max(Double.parseDouble(this.txtMax.getText()));
         /*s.setPerimetro(Double.parseDouble(this.txtPerimetro1.getText()));*/

             
                     if (btnAGRO.isSelected() == true) {
            BF.setTipo("Agroquimico");
        }
        else if (btnFER.isSelected()==true) {
            BF.setTipo("Fertilizante");
        }
          if (btnActivo.isSelected() == true) {
            BF.setEstado("Activo");
        }
        else if (btnInactivo.isSelected()==true) {
            BF.setEstado("Inactivo");
        }
        /*Cambiar el controlador LaborC*/
        if (controlador.B_FAQC.isRegister(BF )) {
            /*Cambiar el controlador LaborC*/
            controlador.B_FAQC.setListar("");
            JOptionPane.showMessageDialog(this, "Exitoso");
        }
         else{
            JOptionPane.showMessageDialog(this, "Error");
        }
 
           
    }//GEN-LAST:event_guardarMouseClicked

    private void btnAGROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAGROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAGROActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
            char c= evt.getKeyChar();
            if((c<'a' ||c>'z') && (c<'A') |c>'Z')evt.consume(); 
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaxKeyTyped
            char c= evt.getKeyChar();
       if(c<'0' ||c>'9')evt.consume();
    }//GEN-LAST:event_txtMaxKeyTyped

    private void txtActKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtActKeyTyped
            char c= evt.getKeyChar();
       if(c<'0' ||c>'9')evt.consume();
    }//GEN-LAST:event_txtActKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBodega3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBodega3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBodega3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBodega3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBodega3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSRadioButtonMaterial btnAGRO;
    private RSMaterialComponent.RSRadioButtonMaterial btnActivo;
    private newscomponents.RSButtonFlat_new btnCancelarRiego1;
    private RSMaterialComponent.RSRadioButtonMaterial btnFER;
    private RSMaterialComponent.RSRadioButtonMaterial btnInactivo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private newscomponents.RSButtonFlat_new guardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFechaRiego;
    private javax.swing.JLabel lblHoraRiego;
    private javax.swing.JLabel lblHoraRiego1;
    private javax.swing.JLabel lblPersonalRiego;
    private javax.swing.JLabel lblPersonalRiego1;
    private RSMaterialComponent.RSTextFieldMaterial txtAct;
    private RSMaterialComponent.RSTextFieldMaterial txtMax;
    private RSMaterialComponent.RSTextFieldMaterial txtNombre;
    // End of variables declaration//GEN-END:variables
}
