package yumsystem;

import javax.swing.JOptionPane;
import modelo.B_FAQ;
import controlador.B_FAQC;

public class frmBodega3Update extends javax.swing.JFrame {

    /**
     * Creates new form frmBodega3
     */
    public frmBodega3Update() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFechaRiego = new javax.swing.JLabel();
        txtFER = new RSMaterialComponent.RSTextFieldMaterial();
        lblHoraRiego = new javax.swing.JLabel();
        lblPersonalRiego = new javax.swing.JLabel();
        txtMax = new RSMaterialComponent.RSTextFieldMaterial();
        guardar = new newscomponents.RSButtonFlat_new();
        btnCancelarRiego1 = new newscomponents.RSButtonFlat_new();
        txtAct = new RSMaterialComponent.RSTextFieldMaterial();
        lblPersonalRiego1 = new javax.swing.JLabel();
        cmbFer = new RSMaterialComponent.RSComboBox();
        cmbEstado = new RSMaterialComponent.RSComboBox();
        lblHoraRiego2 = new javax.swing.JLabel();
        lblRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(149, 160, 95));

        lblFechaRiego.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaRiego.setText("Nombre:");

        txtFER.setBackground(new java.awt.Color(242, 242, 242));
        txtFER.setForeground(new java.awt.Color(0, 0, 0));
        txtFER.setColorMaterial(new java.awt.Color(0, 114, 81));
        txtFER.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFER.setPhColor(new java.awt.Color(102, 102, 102));
        txtFER.setPlaceholder("Fertilizante y agroquimico");
        txtFER.setSelectionColor(new java.awt.Color(0, 114, 81));
        txtFER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFERActionPerformed(evt);
            }
        });
        txtFER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFERKeyTyped(evt);
            }
        });

        lblHoraRiego.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHoraRiego.setText("Cantidad maxima:");

        lblPersonalRiego.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPersonalRiego.setText("Tipo:");

        txtMax.setBackground(new java.awt.Color(242, 242, 242));
        txtMax.setForeground(new java.awt.Color(0, 0, 0));
        txtMax.setColorMaterial(new java.awt.Color(0, 114, 81));
        txtMax.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMax.setPhColor(new java.awt.Color(102, 102, 102));
        txtMax.setPlaceholder("Maximo");
        txtMax.setSelectionColor(new java.awt.Color(0, 114, 81));
        txtMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaxKeyTyped(evt);
            }
        });

        guardar.setBackground(new java.awt.Color(0, 114, 81));
        guardar.setText("Actulizar");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });

        btnCancelarRiego1.setBackground(new java.awt.Color(0, 114, 81));
        btnCancelarRiego1.setText("Cancelar");
        btnCancelarRiego1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarRiego1MouseClicked(evt);
            }
        });

        txtAct.setBackground(new java.awt.Color(242, 242, 242));
        txtAct.setForeground(new java.awt.Color(0, 0, 0));
        txtAct.setColorMaterial(new java.awt.Color(0, 114, 81));
        txtAct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAct.setPhColor(new java.awt.Color(102, 102, 102));
        txtAct.setPlaceholder("Actual");
        txtAct.setSelectionColor(new java.awt.Color(0, 114, 81));
        txtAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtActKeyTyped(evt);
            }
        });

        lblPersonalRiego1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPersonalRiego1.setText("Estado");

        cmbFer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fertilizante ", "Agroquimico", " " }));
        cmbFer.setColorArrow(new java.awt.Color(0, 114, 81));
        cmbFer.setColorFondo(new java.awt.Color(0, 114, 81));
        cmbFer.setColorSeleccion(new java.awt.Color(0, 114, 81));
        cmbFer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        cmbEstado.setColorArrow(new java.awt.Color(0, 114, 81));
        cmbEstado.setColorFondo(new java.awt.Color(0, 114, 81));
        cmbEstado.setColorSeleccion(new java.awt.Color(0, 114, 81));
        cmbEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblHoraRiego2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHoraRiego2.setText("Cantidad Actual:");

        lblRegistro.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblRegistro.setForeground(new java.awt.Color(0, 114, 81));
        lblRegistro.setText("ACTUALIZAR FAQ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtFER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAct, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarRiego1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPersonalRiego)
                                .addGap(172, 172, 172)
                                .addComponent(lblPersonalRiego1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmbFer, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(37, 37, 37)
                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblHoraRiego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHoraRiego2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFechaRiego)
                        .addGap(0, 282, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistro)
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblRegistro)
                .addGap(32, 32, 32)
                .addComponent(lblFechaRiego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraRiego)
                    .addComponent(lblHoraRiego2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonalRiego)
                    .addComponent(lblPersonalRiego1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarRiego1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFERActionPerformed

    private void btnCancelarRiego1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarRiego1MouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarRiego1MouseClicked

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
        /*Cambiar el modelo*/

        if (txtFER.getText().equals("") || txtAct.getText().equals("")
                || txtMax.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Porfavor llene todos los datos");

        } else {
            modelo.B_FAQ BF = new modelo.B_FAQ();
            /*Aplicar los set correspondientes al modelo*/
            BF.setNombre(this.txtFER.getText());
            BF.setCantidad_Max(Double.parseDouble(this.txtMax.getText()));
            BF.setCantidad_Actual(Double.parseDouble(this.txtAct.getText()));

            BF.setEstado(this.cmbEstado.getSelectedItem().toString());
            BF.setTipo(this.cmbFer.getSelectedItem().toString());
            /*Cambiar el controlador LaborC*/
            if (controlador.B_FAQC.isUpdate(BF)) {
                /*Cambiar el controlador LaborC*/
                controlador.B_FAQC.setListar("");
                JOptionPane.showMessageDialog(this, "Exitoso");
            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }

        }
    }//GEN-LAST:event_guardarMouseClicked

    private void txtFERKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFERKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A') | c > 'Z') {
            evt.consume();
        }
    }//GEN-LAST:event_txtFERKeyTyped

    private void txtMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaxKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtMaxKeyTyped

    private void txtActKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtActKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtActKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBodega3Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBodega3Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBodega3Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBodega3Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBodega3Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private newscomponents.RSButtonFlat_new btnCancelarRiego1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static RSMaterialComponent.RSComboBox cmbEstado;
    public static RSMaterialComponent.RSComboBox cmbFer;
    private newscomponents.RSButtonFlat_new guardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFechaRiego;
    private javax.swing.JLabel lblHoraRiego;
    private javax.swing.JLabel lblHoraRiego2;
    private javax.swing.JLabel lblPersonalRiego;
    private javax.swing.JLabel lblPersonalRiego1;
    private javax.swing.JLabel lblRegistro;
    public static RSMaterialComponent.RSTextFieldMaterial txtAct;
    public static RSMaterialComponent.RSTextFieldMaterial txtFER;
    public static RSMaterialComponent.RSTextFieldMaterial txtMax;
    // End of variables declaration//GEN-END:variables
}
