package yumsystem;

/**
 *
 * @author Rodri
 */
public class frmCultivo3 extends javax.swing.JFrame {

    /**
     * Creates new form frmCultivo3
     */
    public frmCultivo3() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtHoraRiego = new RSMaterialComponent.RSTextFieldMaterial();
        lblHoraRiego = new javax.swing.JLabel();
        lblPersonalRiego = new javax.swing.JLabel();
        btnAgregarRiego = new newscomponents.RSButtonFlat_new();
        btnCancelarRiego1 = new newscomponents.RSButtonFlat_new();
        rSComboBox3 = new RSMaterialComponent.RSComboBox();
        lblHoraRiego1 = new javax.swing.JLabel();
        rSComboBox4 = new RSMaterialComponent.RSComboBox();
        lblPersonalRiego1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rSComboBox5 = new RSMaterialComponent.RSComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnAgregarRiego1 = new newscomponents.RSButtonFlat_new();
        btnAgregarRiego2 = new newscomponents.RSButtonFlat_new();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(149, 160, 95));

        txtHoraRiego.setBackground(new java.awt.Color(242, 242, 242));
        txtHoraRiego.setForeground(new java.awt.Color(0, 0, 0));
        txtHoraRiego.setColorMaterial(new java.awt.Color(0, 114, 81));
        txtHoraRiego.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtHoraRiego.setPhColor(new java.awt.Color(102, 102, 102));
        txtHoraRiego.setPlaceholder("Hora de riego");
        txtHoraRiego.setSelectionColor(new java.awt.Color(0, 114, 81));
        txtHoraRiego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraRiegoActionPerformed(evt);
            }
        });

        lblHoraRiego.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHoraRiego.setText("Hora de riego:");

        lblPersonalRiego.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPersonalRiego.setText("Personal a agregar:");

        btnAgregarRiego.setBackground(new java.awt.Color(0, 114, 81));
        btnAgregarRiego.setText("Agregar riego");
        btnAgregarRiego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarRiegoMouseClicked(evt);
            }
        });

        btnCancelarRiego1.setBackground(new java.awt.Color(0, 114, 81));
        btnCancelarRiego1.setText("Cancelar");
        btnCancelarRiego1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarRiego1MouseClicked(evt);
            }
        });
        btnCancelarRiego1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRiego1ActionPerformed(evt);
            }
        });

        rSComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        rSComboBox3.setColorArrow(new java.awt.Color(0, 114, 81));
        rSComboBox3.setColorFondo(new java.awt.Color(0, 114, 81));
        rSComboBox3.setColorSeleccion(new java.awt.Color(0, 114, 81));
        rSComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblHoraRiego1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHoraRiego1.setText("Maquinaria:");

        rSComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "invierno" }));
        rSComboBox4.setColorArrow(new java.awt.Color(0, 114, 81));
        rSComboBox4.setColorFondo(new java.awt.Color(0, 114, 81));
        rSComboBox4.setColorSeleccion(new java.awt.Color(0, 114, 81));
        rSComboBox4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblPersonalRiego1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPersonalRiego1.setText("Codigo de parcela: ");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        rSComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "invierno" }));
        rSComboBox5.setColorArrow(new java.awt.Color(0, 114, 81));
        rSComboBox5.setColorFondo(new java.awt.Color(0, 114, 81));
        rSComboBox5.setColorSeleccion(new java.awt.Color(0, 114, 81));
        rSComboBox5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jList1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        btnAgregarRiego1.setBackground(new java.awt.Color(0, 114, 81));
        btnAgregarRiego1.setText("Eliminar");

        btnAgregarRiego2.setBackground(new java.awt.Color(0, 114, 81));
        btnAgregarRiego2.setText("Agregar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rSComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoraRiego, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHoraRiego)
                            .addComponent(lblHoraRiego1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPersonalRiego1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rSComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAgregarRiego, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSComboBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblPersonalRiego)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAgregarRiego2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnAgregarRiego1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelarRiego1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblHoraRiego)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHoraRiego, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblHoraRiego1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rSComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPersonalRiego1)
                                    .addComponent(rSComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPersonalRiego)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAgregarRiego1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgregarRiego2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarRiego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarRiego1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoraRiegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraRiegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraRiegoActionPerformed

    private void btnCancelarRiego1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRiego1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarRiego1ActionPerformed

    private void btnCancelarRiego1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarRiego1MouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarRiego1MouseClicked

    private void btnAgregarRiegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarRiegoMouseClicked
        
    }//GEN-LAST:event_btnAgregarRiegoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCultivo3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCultivo3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCultivo3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCultivo3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCultivo3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private newscomponents.RSButtonFlat_new btnAgregarRiego;
    private newscomponents.RSButtonFlat_new btnAgregarRiego1;
    private newscomponents.RSButtonFlat_new btnAgregarRiego2;
    private newscomponents.RSButtonFlat_new btnCancelarRiego1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblHoraRiego;
    private javax.swing.JLabel lblHoraRiego1;
    private javax.swing.JLabel lblPersonalRiego;
    private javax.swing.JLabel lblPersonalRiego1;
    private RSMaterialComponent.RSComboBox rSComboBox3;
    private RSMaterialComponent.RSComboBox rSComboBox4;
    private RSMaterialComponent.RSComboBox rSComboBox5;
    private RSMaterialComponent.RSTextFieldMaterial txtHoraRiego;
    // End of variables declaration//GEN-END:variables
}
