package yumsystem;


/**
 *
 * @author Rodri
 */
public class frmPersonal extends javax.swing.JFrame {

    /** Creates new form frmPersonal */
    public frmPersonal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblPrimApe = new javax.swing.JLabel();
        txtPrimApe = new RSMaterialComponent.RSTextFieldMaterial();
        lblPrimNom = new javax.swing.JLabel();
        txtPrimNom = new RSMaterialComponent.RSTextFieldMaterial();
        lblSeguNom = new javax.swing.JLabel();
        txtSeguNom = new RSMaterialComponent.RSTextFieldMaterial();
        lblSeguApe = new javax.swing.JLabel();
        txtDuiPers = new RSMaterialComponent.RSTextFieldMaterial();
        lblGenPers = new javax.swing.JLabel();
        txtSeguApe = new RSMaterialComponent.RSTextFieldMaterial();
        btnCancelarPers = new newscomponents.RSButtonFlat_new();
        btnAgPers1 = new newscomponents.RSButtonFlat_new();
        lblDuiPers1 = new javax.swing.JLabel();
        lblFechaNac = new javax.swing.JLabel();
        rsdFechaSiembra = new newscomponents.RSDateChooser();
        rdFem = new RSMaterialComponent.RSRadioButtonMaterial();
        rdMasc = new RSMaterialComponent.RSRadioButtonMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(149, 160, 95));

        lblPrimApe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrimApe.setText("Primer apellido:");

        txtPrimApe.setBackground(new java.awt.Color(242, 242, 242));
        txtPrimApe.setForeground(new java.awt.Color(0, 0, 0));
        txtPrimApe.setColorMaterial(new java.awt.Color(0, 114, 81));
        txtPrimApe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPrimApe.setPhColor(new java.awt.Color(102, 102, 102));
        txtPrimApe.setPlaceholder("Apellido personal");
        txtPrimApe.setSelectionColor(new java.awt.Color(0, 114, 81));
        txtPrimApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimApeActionPerformed(evt);
            }
        });

        lblPrimNom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrimNom.setText("Primer nombre:");

        txtPrimNom.setBackground(new java.awt.Color(242, 242, 242));
        txtPrimNom.setForeground(new java.awt.Color(0, 0, 0));
        txtPrimNom.setColorMaterial(new java.awt.Color(0, 114, 81));
        txtPrimNom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPrimNom.setPhColor(new java.awt.Color(102, 102, 102));
        txtPrimNom.setPlaceholder("Nombre Personal");
        txtPrimNom.setSelectionColor(new java.awt.Color(0, 114, 81));
        txtPrimNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimNomActionPerformed(evt);
            }
        });

        lblSeguNom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSeguNom.setText("Segundo nombre:");

        txtSeguNom.setBackground(new java.awt.Color(242, 242, 242));
        txtSeguNom.setForeground(new java.awt.Color(0, 0, 0));
        txtSeguNom.setColorMaterial(new java.awt.Color(0, 114, 81));
        txtSeguNom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSeguNom.setPhColor(new java.awt.Color(102, 102, 102));
        txtSeguNom.setPlaceholder("Nombre Personal");
        txtSeguNom.setSelectionColor(new java.awt.Color(0, 114, 81));
        txtSeguNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeguNomActionPerformed(evt);
            }
        });

        lblSeguApe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSeguApe.setText("Segundo Apellido:");

        txtDuiPers.setBackground(new java.awt.Color(242, 242, 242));
        txtDuiPers.setForeground(new java.awt.Color(0, 0, 0));
        txtDuiPers.setColorMaterial(new java.awt.Color(0, 114, 81));
        txtDuiPers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDuiPers.setPhColor(new java.awt.Color(102, 102, 102));
        txtDuiPers.setPlaceholder("DUI");
        txtDuiPers.setSelectionColor(new java.awt.Color(0, 114, 81));
        txtDuiPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuiPersActionPerformed(evt);
            }
        });

        lblGenPers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGenPers.setText("Genero:");

        txtSeguApe.setBackground(new java.awt.Color(242, 242, 242));
        txtSeguApe.setForeground(new java.awt.Color(0, 0, 0));
        txtSeguApe.setColorMaterial(new java.awt.Color(0, 114, 81));
        txtSeguApe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSeguApe.setPhColor(new java.awt.Color(102, 102, 102));
        txtSeguApe.setPlaceholder("Apellido personal");
        txtSeguApe.setSelectionColor(new java.awt.Color(0, 114, 81));
        txtSeguApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeguApeActionPerformed(evt);
            }
        });

        btnCancelarPers.setBackground(new java.awt.Color(0, 114, 81));
        btnCancelarPers.setText("Cancelar");
        btnCancelarPers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarPersMouseClicked(evt);
            }
        });

        btnAgPers1.setBackground(new java.awt.Color(0, 114, 81));
        btnAgPers1.setText("Agregar personal");
        btnAgPers1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgPers1MouseClicked(evt);
            }
        });

        lblDuiPers1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDuiPers1.setText("DUI:");

        lblFechaNac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaNac.setText("Fecha de Nacimiento:");

        rsdFechaSiembra.setBackground(new java.awt.Color(76, 164, 86));
        rsdFechaSiembra.setBgColor(new java.awt.Color(76, 164, 86));
        rsdFechaSiembra.setDate(new java.util.Date(1622440800000L));

        buttonGroup1.add(rdFem);
        rdFem.setForeground(new java.awt.Color(0, 114, 81));
        rdFem.setText("Femenino");
        rdFem.setColorCheck(new java.awt.Color(122, 201, 104));
        rdFem.setColorUnCheck(new java.awt.Color(0, 114, 81));

        buttonGroup1.add(rdMasc);
        rdMasc.setForeground(new java.awt.Color(0, 114, 81));
        rdMasc.setText("Masculino");
        rdMasc.setColorCheck(new java.awt.Color(122, 201, 104));
        rdMasc.setColorUnCheck(new java.awt.Color(0, 114, 81));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrimNom, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPrimApe)
                                            .addComponent(txtPrimApe, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDuiPers1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblFechaNac))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblPrimNom))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtDuiPers, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSeguApe, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(lblSeguApe, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSeguNom, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSeguNom, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCancelarPers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(lblGenPers)
                                                .addGap(123, 123, 123))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(rdMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rdFem, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgPers1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rsdFechaSiembra, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeguNom)
                    .addComponent(lblPrimNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeguNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrimNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimApe)
                    .addComponent(lblSeguApe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrimApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSeguApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblGenPers))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDuiPers1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDuiPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdFem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(lblFechaNac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rsdFechaSiembra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgPers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrimApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimApeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimApeActionPerformed

    private void txtPrimNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimNomActionPerformed

    private void txtSeguNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeguNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeguNomActionPerformed

    private void txtDuiPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuiPersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuiPersActionPerformed

    private void txtSeguApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeguApeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeguApeActionPerformed

    private void btnCancelarPersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarPersMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarPersMouseClicked

    private void btnAgPers1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgPers1MouseClicked
        
    }//GEN-LAST:event_btnAgPers1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private newscomponents.RSButtonFlat_new btnAgPers1;
    private newscomponents.RSButtonFlat_new btnCancelarPers;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDuiPers1;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblGenPers;
    private javax.swing.JLabel lblPrimApe;
    private javax.swing.JLabel lblPrimNom;
    private javax.swing.JLabel lblSeguApe;
    private javax.swing.JLabel lblSeguNom;
    private RSMaterialComponent.RSRadioButtonMaterial rdFem;
    private RSMaterialComponent.RSRadioButtonMaterial rdMasc;
    private newscomponents.RSDateChooser rsdFechaSiembra;
    private RSMaterialComponent.RSTextFieldMaterial txtDuiPers;
    private RSMaterialComponent.RSTextFieldMaterial txtPrimApe;
    private RSMaterialComponent.RSTextFieldMaterial txtPrimNom;
    private RSMaterialComponent.RSTextFieldMaterial txtSeguApe;
    private RSMaterialComponent.RSTextFieldMaterial txtSeguNom;
    // End of variables declaration//GEN-END:variables

}
