/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subPanel;

/**
 *
 * @author Rodri
 */
public class pnlConfiguracion4 extends javax.swing.JPanel {

    /**
     * Creates new form pnlConfiguracion4
     */
    public pnlConfiguracion4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpCultivo = new javax.swing.ButtonGroup();
        groPersonal = new javax.swing.ButtonGroup();
        grpParcela = new javax.swing.ButtonGroup();
        grpBodega = new javax.swing.ButtonGroup();
        grpReportes = new javax.swing.ButtonGroup();
        grpConfiguracion = new javax.swing.ButtonGroup();
        rSPanelOpacity1 = new newscomponents.RSPanelOpacity();
        rSPanelOpacity2 = new newscomponents.RSPanelOpacity();
        rSButtonFlat_new1 = new newscomponents.RSButtonFlat_new();
        rSPanelOpacity3 = new newscomponents.RSPanelOpacity();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        rSComboBox1 = new RSMaterialComponent.RSComboBox();
        jLabel1 = new javax.swing.JLabel();
        rSPanelOpacity4 = new newscomponents.RSPanelOpacity();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        rSPanelOpacity5 = new newscomponents.RSPanelOpacity();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        rSPanelOpacity6 = new newscomponents.RSPanelOpacity();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        rSPanelOpacity7 = new newscomponents.RSPanelOpacity();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(225, 232, 193));

        rSPanelOpacity1.setBackground(new java.awt.Color(242, 242, 242));

        rSPanelOpacity2.setBackground(new java.awt.Color(242, 242, 242));
        rSPanelOpacity2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2), "Personalizar rol de usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        rSButtonFlat_new1.setBackground(new java.awt.Color(76, 164, 86));
        rSButtonFlat_new1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_joyent_30px_2.png"))); // NOI18N
        rSButtonFlat_new1.setText("Agregar Rol");
        rSButtonFlat_new1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonFlat_new1MouseClicked(evt);
            }
        });

        rSPanelOpacity3.setBackground(new java.awt.Color(242, 242, 242));
        rSPanelOpacity3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cultivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(35, 35, 35))); // NOI18N

        jCheckBox1.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox1);
        jCheckBox1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox1.setText("Agregar nuevo cultivo");

        jCheckBox3.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox3);
        jCheckBox3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox3.setText("Editar Cultivo");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox5.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox5);
        jCheckBox5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox5.setText("Ver registro de cultivos");

        jCheckBox9.setBackground(new java.awt.Color(242, 242, 242));
        jCheckBox9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox9.setText("Todo el modulo");

        jCheckBox4.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox4);
        jCheckBox4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox4.setText("Agregar registro de riego");
        jCheckBox4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox14.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox14);
        jCheckBox14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox14.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox14.setText("Ver Registro de riego");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jCheckBox15.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox15);
        jCheckBox15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox15.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox15.setText("Editar registro de riego");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelOpacity3Layout = new javax.swing.GroupLayout(rSPanelOpacity3);
        rSPanelOpacity3.setLayout(rSPanelOpacity3Layout);
        rSPanelOpacity3Layout.setHorizontalGroup(
            rSPanelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelOpacity3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelOpacity3Layout.createSequentialGroup()
                        .addComponent(jCheckBox9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelOpacity3Layout.createSequentialGroup()
                        .addGroup(rSPanelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox15)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(rSPanelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox14)
                            .addComponent(jCheckBox4))
                        .addGap(61, 61, 61))))
        );
        rSPanelOpacity3Layout.setVerticalGroup(
            rSPanelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelOpacity3Layout.createSequentialGroup()
                .addComponent(jCheckBox9)
                .addGap(18, 18, 18)
                .addGroup(rSPanelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelOpacity3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox15))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        rSComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "RSItem 2", "RSItem 3", "RSItem 4" }));
        rSComboBox1.setColorArrow(new java.awt.Color(76, 164, 86));
        rSComboBox1.setColorBorde(new java.awt.Color(122, 201, 104));
        rSComboBox1.setColorFondo(new java.awt.Color(76, 164, 86));
        rSComboBox1.setColorSeleccion(new java.awt.Color(122, 201, 104));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Selecciona el rol a editar:");

        rSPanelOpacity4.setBackground(new java.awt.Color(242, 242, 242));
        rSPanelOpacity4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(35, 35, 35))); // NOI18N

        jCheckBox6.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox6);
        jCheckBox6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox6.setText("Agregar nuevo Personal");

        jCheckBox7.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox7);
        jCheckBox7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox7.setText("Ver personal");

        jCheckBox8.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox8);
        jCheckBox8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox8.setText("Editar Personal");

        jCheckBox10.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox10);
        jCheckBox10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox10.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox10.setText("Todo el modulo");

        jCheckBox11.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox11);
        jCheckBox11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox11.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox11.setText("Nuevo registro de labores");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });

        jCheckBox12.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox12);
        jCheckBox12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox12.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox12.setText("Ver registro de labores");

        jCheckBox13.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox13);
        jCheckBox13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox13.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox13.setText("Editar registro de labores");

        javax.swing.GroupLayout rSPanelOpacity4Layout = new javax.swing.GroupLayout(rSPanelOpacity4);
        rSPanelOpacity4.setLayout(rSPanelOpacity4Layout);
        rSPanelOpacity4Layout.setHorizontalGroup(
            rSPanelOpacity4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelOpacity4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelOpacity4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelOpacity4Layout.createSequentialGroup()
                        .addGroup(rSPanelOpacity4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox12)
                            .addComponent(jCheckBox8))
                        .addGap(135, 135, 135)
                        .addGroup(rSPanelOpacity4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox13)
                            .addComponent(jCheckBox11)
                            .addComponent(jCheckBox7)))
                    .addComponent(jCheckBox10))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        rSPanelOpacity4Layout.setVerticalGroup(
            rSPanelOpacity4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelOpacity4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox10)
                .addGap(18, 18, 18)
                .addGroup(rSPanelOpacity4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rSPanelOpacity4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelOpacity4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox13)
                    .addComponent(jCheckBox12))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        rSPanelOpacity5.setBackground(new java.awt.Color(242, 242, 242));
        rSPanelOpacity5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bodega", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(35, 35, 35))); // NOI18N

        jCheckBox21.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox21);
        jCheckBox21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox21.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox21.setText("Todo el modulo");

        jCheckBox23.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox23);
        jCheckBox23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox23.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox23.setText("Editar insumos");

        jCheckBox24.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox24);
        jCheckBox24.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox24.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox24.setText("Modificar insumos");

        jCheckBox25.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox25);
        jCheckBox25.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox25.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox25.setText("Ver Insumos");

        jCheckBox26.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox26);
        jCheckBox26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox26.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox26.setText("Editar  cosecha");

        jCheckBox27.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox27);
        jCheckBox27.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox27.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox27.setText("Modificar cosecha");

        jCheckBox28.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox28);
        jCheckBox28.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox28.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox28.setText("Ver Cosecha");

        javax.swing.GroupLayout rSPanelOpacity5Layout = new javax.swing.GroupLayout(rSPanelOpacity5);
        rSPanelOpacity5.setLayout(rSPanelOpacity5Layout);
        rSPanelOpacity5Layout.setHorizontalGroup(
            rSPanelOpacity5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelOpacity5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelOpacity5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelOpacity5Layout.createSequentialGroup()
                        .addComponent(jCheckBox21)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(rSPanelOpacity5Layout.createSequentialGroup()
                        .addComponent(jCheckBox23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox24)
                        .addGap(89, 89, 89))
                    .addGroup(rSPanelOpacity5Layout.createSequentialGroup()
                        .addComponent(jCheckBox25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox26)
                        .addGap(105, 105, 105))
                    .addGroup(rSPanelOpacity5Layout.createSequentialGroup()
                        .addComponent(jCheckBox27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox28)
                        .addGap(121, 121, 121))))
        );
        rSPanelOpacity5Layout.setVerticalGroup(
            rSPanelOpacity5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelOpacity5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox21)
                .addGap(18, 18, 18)
                .addGroup(rSPanelOpacity5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox23)
                    .addComponent(jCheckBox24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelOpacity5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox25)
                    .addComponent(jCheckBox26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelOpacity5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox27)
                    .addComponent(jCheckBox28))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSPanelOpacity6.setBackground(new java.awt.Color(242, 242, 242));
        rSPanelOpacity6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parcela", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(35, 35, 35))); // NOI18N

        jCheckBox16.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox16);
        jCheckBox16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox16.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox16.setText("Todo el modulo");

        jCheckBox17.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox17);
        jCheckBox17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox17.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox17.setText("Editar Parcela");

        jCheckBox18.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox18);
        jCheckBox18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox18.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox18.setText("Ver Parcela");

        jCheckBox19.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox19);
        jCheckBox19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox19.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox19.setText("Ver datos de parcela");

        jCheckBox20.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox20);
        jCheckBox20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox20.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox20.setText("Agregar nuevos datos");

        jCheckBox22.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox22);
        jCheckBox22.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox22.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox22.setText("Editar Datos");

        javax.swing.GroupLayout rSPanelOpacity6Layout = new javax.swing.GroupLayout(rSPanelOpacity6);
        rSPanelOpacity6.setLayout(rSPanelOpacity6Layout);
        rSPanelOpacity6Layout.setHorizontalGroup(
            rSPanelOpacity6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelOpacity6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelOpacity6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelOpacity6Layout.createSequentialGroup()
                        .addGroup(rSPanelOpacity6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox19)
                            .addComponent(jCheckBox17))
                        .addGap(162, 162, 162)
                        .addGroup(rSPanelOpacity6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox18)
                            .addComponent(jCheckBox20)))
                    .addComponent(jCheckBox16)
                    .addComponent(jCheckBox22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rSPanelOpacity6Layout.setVerticalGroup(
            rSPanelOpacity6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelOpacity6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox16)
                .addGap(18, 18, 18)
                .addGroup(rSPanelOpacity6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox17)
                    .addComponent(jCheckBox18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelOpacity6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox19)
                    .addComponent(jCheckBox20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox22)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        rSPanelOpacity7.setBackground(new java.awt.Color(242, 242, 242));
        rSPanelOpacity7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reportes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(35, 35, 35))); // NOI18N

        jCheckBox29.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox29);
        jCheckBox29.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox29.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox29.setText("Todo el modulo");

        jCheckBox30.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox30);
        jCheckBox30.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox30.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox30.setText("Ver reportes");

        jCheckBox31.setBackground(new java.awt.Color(242, 242, 242));
        grpCultivo.add(jCheckBox31);
        jCheckBox31.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox31.setForeground(new java.awt.Color(35, 35, 35));
        jCheckBox31.setText("Generar reporte");

        javax.swing.GroupLayout rSPanelOpacity7Layout = new javax.swing.GroupLayout(rSPanelOpacity7);
        rSPanelOpacity7.setLayout(rSPanelOpacity7Layout);
        rSPanelOpacity7Layout.setHorizontalGroup(
            rSPanelOpacity7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelOpacity7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelOpacity7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelOpacity7Layout.createSequentialGroup()
                        .addComponent(jCheckBox29)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(rSPanelOpacity7Layout.createSequentialGroup()
                        .addComponent(jCheckBox31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox30)
                        .addGap(118, 118, 118))))
        );
        rSPanelOpacity7Layout.setVerticalGroup(
            rSPanelOpacity7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelOpacity7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(rSPanelOpacity7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox31)
                    .addComponent(jCheckBox30))
                .addContainerGap())
        );

        javax.swing.GroupLayout rSPanelOpacity2Layout = new javax.swing.GroupLayout(rSPanelOpacity2);
        rSPanelOpacity2.setLayout(rSPanelOpacity2Layout);
        rSPanelOpacity2Layout.setHorizontalGroup(
            rSPanelOpacity2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelOpacity2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelOpacity2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelOpacity2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(rSComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSButtonFlat_new1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rSPanelOpacity4, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addComponent(rSPanelOpacity5, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addComponent(rSPanelOpacity6, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addComponent(rSPanelOpacity7, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addComponent(rSPanelOpacity3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
                .addContainerGap())
        );
        rSPanelOpacity2Layout.setVerticalGroup(
            rSPanelOpacity2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelOpacity2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelOpacity2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSButtonFlat_new1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSPanelOpacity3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSPanelOpacity4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSPanelOpacity6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSPanelOpacity5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSPanelOpacity7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rSPanelOpacity1Layout = new javax.swing.GroupLayout(rSPanelOpacity1);
        rSPanelOpacity1.setLayout(rSPanelOpacity1Layout);
        rSPanelOpacity1Layout.setHorizontalGroup(
            rSPanelOpacity1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelOpacity1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelOpacity2, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelOpacity1Layout.setVerticalGroup(
            rSPanelOpacity1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelOpacity1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelOpacity2, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelOpacity1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelOpacity1, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void rSButtonFlat_new1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonFlat_new1MouseClicked
        new yumsystem.frmRol().setVisible(true);
    }//GEN-LAST:event_rSButtonFlat_new1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup groPersonal;
    private javax.swing.ButtonGroup grpBodega;
    private javax.swing.ButtonGroup grpConfiguracion;
    private javax.swing.ButtonGroup grpCultivo;
    private javax.swing.ButtonGroup grpParcela;
    private javax.swing.ButtonGroup grpReportes;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private newscomponents.RSButtonFlat_new rSButtonFlat_new1;
    private RSMaterialComponent.RSComboBox rSComboBox1;
    private newscomponents.RSPanelOpacity rSPanelOpacity1;
    private newscomponents.RSPanelOpacity rSPanelOpacity2;
    private newscomponents.RSPanelOpacity rSPanelOpacity3;
    private newscomponents.RSPanelOpacity rSPanelOpacity4;
    private newscomponents.RSPanelOpacity rSPanelOpacity5;
    private newscomponents.RSPanelOpacity rSPanelOpacity6;
    private newscomponents.RSPanelOpacity rSPanelOpacity7;
    // End of variables declaration//GEN-END:variables
}
