/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subPanel;

/**
 *
 * @author Rodri
 */
public class pnlConfiguracion3 extends javax.swing.JPanel {

    /**
     * Creates new form pnlConfiguracion3
     */
    public pnlConfiguracion3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelOpacity1 = new newscomponents.RSPanelOpacity();
        rSTextFieldIconOne1 = new RSMaterialComponent.RSTextFieldIconOne();
        jScrollPane2 = new javax.swing.JScrollPane();
        rSTableMetroCustom2 = new RSMaterialComponent.RSTableMetroCustom();
        rSButtonFlat_new1 = new newscomponents.RSButtonFlat_new();

        setBackground(new java.awt.Color(225, 232, 193));

        rSPanelOpacity1.setBackground(new java.awt.Color(242, 242, 242));

        rSTextFieldIconOne1.setBackground(new java.awt.Color(242, 242, 242));
        rSTextFieldIconOne1.setForeground(new java.awt.Color(0, 114, 81));
        rSTextFieldIconOne1.setBorderColor(new java.awt.Color(0, 114, 81));
        rSTextFieldIconOne1.setColorIcon(new java.awt.Color(0, 114, 81));
        rSTextFieldIconOne1.setDisabledTextColor(new java.awt.Color(166, 196, 126));
        rSTextFieldIconOne1.setFocusTraversalPolicyProvider(true);
        rSTextFieldIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSTextFieldIconOne1.setPhColor(new java.awt.Color(166, 196, 126));
        rSTextFieldIconOne1.setPlaceholder("Buscar");

        rSTableMetroCustom2.setBackground(new java.awt.Color(209, 226, 171));
        rSTableMetroCustom2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rSTableMetroCustom2.setBackgoundHead(new java.awt.Color(91, 180, 98));
        rSTableMetroCustom2.setBackgoundHover(new java.awt.Color(166, 196, 126));
        rSTableMetroCustom2.setBorderHead(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(91, 180, 98)));
        rSTableMetroCustom2.setBorderRows(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(91, 180, 98)));
        rSTableMetroCustom2.setColorBorderHead(new java.awt.Color(91, 180, 98));
        rSTableMetroCustom2.setColorBorderRows(new java.awt.Color(91, 180, 98));
        rSTableMetroCustom2.setColorPrimaryText(new java.awt.Color(91, 180, 98));
        rSTableMetroCustom2.setColorSecondary(new java.awt.Color(143, 217, 116));
        rSTableMetroCustom2.setColorSecundaryText(new java.awt.Color(0, 102, 255));
        rSTableMetroCustom2.setGridColor(new java.awt.Color(91, 180, 98));
        rSTableMetroCustom2.setSelectionBackground(new java.awt.Color(166, 196, 126));
        jScrollPane2.setViewportView(rSTableMetroCustom2);

        rSButtonFlat_new1.setBackground(new java.awt.Color(0, 114, 81));
        rSButtonFlat_new1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_joyent_30px_2.png"))); // NOI18N
        rSButtonFlat_new1.setText("Registrar Usuario");
        rSButtonFlat_new1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonFlat_new1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rSPanelOpacity1Layout = new javax.swing.GroupLayout(rSPanelOpacity1);
        rSPanelOpacity1.setLayout(rSPanelOpacity1Layout);
        rSPanelOpacity1Layout.setHorizontalGroup(
            rSPanelOpacity1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelOpacity1Layout.createSequentialGroup()
                .addComponent(rSTextFieldIconOne1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(rSButtonFlat_new1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2)
        );
        rSPanelOpacity1Layout.setVerticalGroup(
            rSPanelOpacity1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelOpacity1Layout.createSequentialGroup()
                .addGroup(rSPanelOpacity1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSTextFieldIconOne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonFlat_new1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelOpacity1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelOpacity1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonFlat_new1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonFlat_new1MouseClicked
        new yumsystem.frmUsuario().setVisible(true);
    }//GEN-LAST:event_rSButtonFlat_new1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private newscomponents.RSButtonFlat_new rSButtonFlat_new1;
    private newscomponents.RSPanelOpacity rSPanelOpacity1;
    private RSMaterialComponent.RSTableMetroCustom rSTableMetroCustom2;
    private RSMaterialComponent.RSTextFieldIconOne rSTextFieldIconOne1;
    // End of variables declaration//GEN-END:variables
}
