/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subPanel;

/**
 *
 * @author Rodri
 */
public class pnlCultivo5 extends javax.swing.JPanel {

    /**
     * Creates new form pnlCultivo5
     */
    public pnlCultivo5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscarAgricultura = new RSMaterialComponent.RSTextFieldOne();
        btnAEspecie = new newscomponents.RSButtonFlat_new();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rSDateChooser1 = new newscomponents.RSDateChooser();
        jLabel4 = new javax.swing.JLabel();
        rSDateChooser2 = new newscomponents.RSDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetroCustom1 = new RSMaterialComponent.RSTableMetroCustom();
        rSComboBox1 = new RSMaterialComponent.RSComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(225, 232, 193));

        txtBuscarAgricultura.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscarAgricultura.setBorderColor(new java.awt.Color(0, 204, 51));
        txtBuscarAgricultura.setPlaceholder("Buscar...");
        txtBuscarAgricultura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarAgriculturaActionPerformed(evt);
            }
        });

        btnAEspecie.setBackground(new java.awt.Color(0, 114, 81));
        btnAEspecie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_joyent_30px_2.png"))); // NOI18N
        btnAEspecie.setText("Nueva Cosecha");
        btnAEspecie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAEspecieMouseClicked(evt);
            }
        });
        btnAEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAEspecieActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 55));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_filter_24px_1.png"))); // NOI18N
        jLabel5.setText("Filtros de busqueda:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 55));
        jLabel3.setText("De");

        rSDateChooser1.setBackground(new java.awt.Color(76, 164, 86));
        rSDateChooser1.setBgColor(new java.awt.Color(76, 164, 86));
        rSDateChooser1.setDate(new java.util.Date(1622440800000L));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 55));
        jLabel4.setText("Hasta");

        rSDateChooser2.setBgColor(new java.awt.Color(76, 164, 86));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 55));
        jLabel6.setText("Parcela:");

        rSTableMetroCustom1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rSTableMetroCustom1.setBackgoundHead(new java.awt.Color(91, 180, 98));
        rSTableMetroCustom1.setBorderHead(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(91, 180, 98)));
        rSTableMetroCustom1.setBorderRows(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(91, 180, 98)));
        rSTableMetroCustom1.setColorBorderHead(new java.awt.Color(91, 180, 98));
        rSTableMetroCustom1.setColorBorderRows(new java.awt.Color(91, 180, 98));
        rSTableMetroCustom1.setColorPrimaryText(new java.awt.Color(91, 180, 98));
        rSTableMetroCustom1.setColorSecondary(new java.awt.Color(143, 217, 116));
        rSTableMetroCustom1.setGridColor(new java.awt.Color(91, 180, 98));
        jScrollPane1.setViewportView(rSTableMetroCustom1);

        rSComboBox1.setBackground(new java.awt.Color(204, 255, 204));
        rSComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "RSItem 2", "RSItem 3", "RSItem 4" }));
        rSComboBox1.setColorArrow(new java.awt.Color(76, 164, 86));
        rSComboBox1.setColorBorde(new java.awt.Color(122, 201, 104));
        rSComboBox1.setColorFondo(new java.awt.Color(76, 164, 86));
        rSComboBox1.setColorSeleccion(new java.awt.Color(122, 201, 104));

        jCheckBox1.setBackground(new java.awt.Color(225, 232, 193));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscarAgricultura, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rSComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarAgricultura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarAgriculturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarAgriculturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarAgriculturaActionPerformed

    private void btnAEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAEspecieActionPerformed

    private void btnAEspecieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAEspecieMouseClicked
        new yumsystem.frmCosecha().setVisible(true);
    }//GEN-LAST:event_btnAEspecieMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private newscomponents.RSButtonFlat_new btnAEspecie;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSComboBox rSComboBox1;
    private newscomponents.RSDateChooser rSDateChooser1;
    private newscomponents.RSDateChooser rSDateChooser2;
    private RSMaterialComponent.RSTableMetroCustom rSTableMetroCustom1;
    private RSMaterialComponent.RSTextFieldOne txtBuscarAgricultura;
    // End of variables declaration//GEN-END:variables
}
