package subPanel;

import controlador.ParcelaC;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import modelo.Conexion;

import yumsystem.frmParcela;

public class pnlParcela1 extends javax.swing.JPanel {

    private static modelo.Conexion con = new modelo.Conexion();
    private static Connection conexion = con.getConexion();
    DefaultTableModel model = new DefaultTableModel();  
    PreparedStatement ps = null;
    Statement st = null;
    ResultSet rs = null; 
    
    
    public pnlParcela1() {
        initComponents();
        ParcelaC c;
        ParcelaC.setListar("");
        jPopupMenu1.add(menu);
  
   

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menu = new javax.swing.JPanel();
        btnDelete = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnEdit = new RSMaterialComponent.RSButtonMaterialIconOne();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rSTableMetroCustom2 = new RSMaterialComponent.RSTableMetroCustom();
        rSComboBox2 = new RSMaterialComponent.RSComboBox();
        jLabel7 = new javax.swing.JLabel();
        btnBuscarP = new RSMaterialComponent.RSTextFieldOne();
        btnParcela = new newscomponents.RSButtonFlat_new();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblParcela = new RSMaterialComponent.RSTableMetroCustom();
        jSeparator1 = new javax.swing.JSeparator();

        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelete.setBackground(new java.awt.Color(0, 114, 81));
        btnDelete.setText("Eliminar");
        btnDelete.setComponentPopupMenu(jPopupMenu1);
        btnDelete.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        menu.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, -1));

        btnEdit.setBackground(new java.awt.Color(0, 114, 81));
        btnEdit.setText("Editar");
        btnEdit.setComponentPopupMenu(jPopupMenu1);
        btnEdit.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        menu.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, -1));

        jPanel2.setBackground(new java.awt.Color(225, 232, 193));

        jPanel3.setBackground(new java.awt.Color(225, 232, 193));

        jPanel4.setBackground(new java.awt.Color(242, 242, 242));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Personal designado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(23, 23, 23))); // NOI18N

        rSTableMetroCustom2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rSTableMetroCustom2.setBackgoundHead(new java.awt.Color(91, 180, 98));
        rSTableMetroCustom2.setBorderHead(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(91, 180, 98)));
        rSTableMetroCustom2.setBorderRows(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(91, 180, 98)));
        rSTableMetroCustom2.setColorBorderHead(new java.awt.Color(91, 180, 98));
        rSTableMetroCustom2.setColorBorderRows(new java.awt.Color(91, 180, 98));
        rSTableMetroCustom2.setColorPrimaryText(new java.awt.Color(91, 180, 98));
        rSTableMetroCustom2.setColorSecondary(new java.awt.Color(143, 217, 116));
        rSTableMetroCustom2.setGridColor(new java.awt.Color(91, 180, 98));
        jScrollPane2.setViewportView(rSTableMetroCustom2);

        rSComboBox2.setBackground(new java.awt.Color(204, 255, 204));
        rSComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "RSItem 2", "RSItem 3", "RSItem 4" }));
        rSComboBox2.setColorArrow(new java.awt.Color(76, 164, 86));
        rSComboBox2.setColorBorde(new java.awt.Color(122, 201, 104));
        rSComboBox2.setColorFondo(new java.awt.Color(76, 164, 86));
        rSComboBox2.setColorSeleccion(new java.awt.Color(122, 201, 104));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 55));
        jLabel7.setText("Escoja la parcela:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnBuscarP.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarP.setBorderColor(new java.awt.Color(0, 204, 51));
        btnBuscarP.setPlaceholder("Buscar...");
        btnBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPActionPerformed(evt);
            }
        });
        btnBuscarP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnBuscarPKeyTyped(evt);
            }
        });

        btnParcela.setBackground(new java.awt.Color(0, 114, 81));
        btnParcela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_joyent_30px_2.png"))); // NOI18N
        btnParcela.setText("Nueva Parcela");
        btnParcela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnParcelaMouseClicked(evt);
            }
        });
        btnParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcelaActionPerformed(evt);
            }
        });

        tblParcela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigoParcela", "perimetro", "tipoTierra", "estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblParcela.setBackgoundHead(new java.awt.Color(91, 180, 98));
        tblParcela.setBorderHead(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(91, 180, 98)));
        tblParcela.setBorderRows(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(91, 180, 98)));
        tblParcela.setColorBorderHead(new java.awt.Color(91, 180, 98));
        tblParcela.setColorBorderRows(new java.awt.Color(91, 180, 98));
        tblParcela.setColorPrimaryText(new java.awt.Color(91, 180, 98));
        tblParcela.setColorSecondary(new java.awt.Color(143, 217, 116));
        tblParcela.setComponentPopupMenu(jPopupMenu1);
        tblParcela.setGridColor(new java.awt.Color(91, 180, 98));
        tblParcela.getTableHeader().setReorderingAllowed(false);
        tblParcela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblParcelaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblParcela);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnParcela, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(396, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnParcelaActionPerformed

    private void btnBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPActionPerformed

    private void btnParcelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnParcelaMouseClicked
        new yumsystem.frmParcela ().setVisible(true);
    }//GEN-LAST:event_btnParcelaMouseClicked

    private void btnBuscarPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarPKeyTyped

    }//GEN-LAST:event_btnBuscarPKeyTyped

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
     
        //int fila= tblParcela.getSelectedRow();
        //yumsystem.frmParcelaUpdate Parcela = new yumsystem.frmParcelaUpdate();
        
       // Parcela.txtPerimetro1.setText(tblParcela.getValueAt(fila, 1).toString());               
        //Parcela.txtTipot.setText(tblParcela.getValueAt(fila, 2).toString());//
        
        
    }//GEN-LAST:event_btnEditMouseClicked

    private void tblParcelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblParcelaMouseClicked
       
  
    }//GEN-LAST:event_tblParcelaMouseClicked

    private void btnBuscarPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarPKeyPressed
       
    
        String[] titulos = {"codigoParcela", "perimetro","tipoTierra", "Estado"};
        String[] registros = new String[200];
        String sql = "SELECT * FROM Parcela WHERE codigoParcela LIKE '%" + btnBuscarP.getText() + "%' "
        + "OR tipoTierra LIKE '%" + btnBuscarP.getText() + "%'"
        + "OR estado LIKE '%" + btnBuscarP.getText() + "%'";
        
        model = new DefaultTableModel(null,titulos);
        Connection conexion = con.getConexion();
        
        try
        {
            st = (Statement) conexion.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next())
            {
                registros[0] = rs.getString("codigoParcela");
                registros[1] = rs.getString("perimetro");
                registros[2] = rs.getString("tipoTierra");
                registros[3] = rs.getString("estado");
                model.addRow(registros);
            }
            tblParcela.setModel(model);
        } catch (SQLException ex)
        {
            System.out.println("ERROR AL BUSCAR LOS DATOS : " + ex.getMessage());
        }    

    }//GEN-LAST:event_btnBuscarPKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSTextFieldOne btnBuscarP;
    private RSMaterialComponent.RSButtonMaterialIconOne btnDelete;
    private RSMaterialComponent.RSButtonMaterialIconOne btnEdit;
    private newscomponents.RSButtonFlat_new btnParcela;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menu;
    private RSMaterialComponent.RSComboBox rSComboBox2;
    private RSMaterialComponent.RSTableMetroCustom rSTableMetroCustom2;
    public static RSMaterialComponent.RSTableMetroCustom tblParcela;
    // End of variables declaration//GEN-END:variables
}
